@echo off
echo Starting Intelligent Defense System (Backend + Frontend)...
echo.
echo Starting Backend Server...
start "Backend Server" cmd /k "cd server && npm install && npm run dev"
echo.
echo Waiting 5 seconds for backend to start...
timeout /t 5 /nobreak > nul
echo.
echo Starting Frontend Server...
start "Frontend Server" cmd /k "cd client && npm install && npm run dev"
echo.
echo Both servers are starting...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:5173
echo.
echo Press any key to exit...
pause > nul
