FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --only=production || npm i --only=production
COPY . .
ENV NODE_ENV=production
EXPOSE 5000
CMD ["node", "index.js"]




