version: '3.9'
services:
  api:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017/aegis
      - JWT_SECRET=devsecret
      - NODE_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:




